In [1]:
import numpy as np
import pandas as pd

In [2]:
cd ml-100k/

C:\Users\jc\ml-100k


In [3]:
names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('u.data', sep='\t', names=names)
df.head()

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [4]:
n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print str(n_users) + ' users'
print str(n_items) + ' items'

943 users
1682 items


In [5]:
ratings = np.zeros((n_users, n_items))
for row in df.itertuples():
    ratings[row[1]-1, row[2]-1] = row[3]
ratings

array([[ 5.,  3.,  4., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  5.,  0., ...,  0.,  0.,  0.]])

In [6]:
for row in df.itertuples():
    ratings[row[1]-1, row[2]-1] = row[3]
ratings
ratingsdf=pd.DataFrame(ratings)
ratingsdf.head(5)

0     1     2     3     4     5     6     7     8     9     ...   1672  \
0   5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...    0.0   
1   4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...    0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4   4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   

   1673  1674  1675  1676  1677  1678  1679  1680  1681  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1682 columns]

In [7]:
sparsity = float(len(ratings.nonzero()[0]))
sparsity /= (ratings.shape[0] * ratings.shape[1])
sparsity *= 100
print 'Sparsity: {:4.2f}%'.format(sparsity)

Sparsity: 6.30%


In [8]:
from sklearn import cross_validation as cv
train_data, test_data = cv.train_test_split(df, test_size=0.25)

C:\Users\jc\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
test_data

user_id  item_id  rating  timestamp
69355      796      628       4  893194740
74570      361      319       5  879440941
93789      655     1011       3  887651060
38852      276      281       3  874787065
36990      459      333       3  879561574
472        257      137       4  882049932
58278      158      562       4  880134607
32812      194      467       5  879521253
63901      567      297       3  882426246
23281      222      378       1  881059993
98263      870      746       3  879270400
39344      524      469       4  884636416
8620       109      200       2  880577734
98779      749      739       3  878848558
71857      890     1039       4  882403122
72431      633       77       3  877212173
90965      710      420       4  882064434
14637      374      932       1  883628159
90360      806      231       3  882390614
64449      268      940       2  875743888
53724      425      168       5  890347172
54462       75      322       1  884049789
97508      924      402       3  886759965
35915      272      423       4  879454939
5969       241      307       4  887249795
66677      704      661       4  891397667
20206      180      729       5  877355598
14565      406      588       4  879793081
20868      295      720       4  879518801
87162      908      223       4  879722953
...        ...      ...     ...        ...
70598       94      423       4  885873302
13466      405      414       1  885547268
41128      608      961       4  880405431
18239      294      825       3  877820272
6221       222       40       1  881060550
76329      764        4       3  876245421
60557      184      473       4  889908133
5452       205      333       4  888284618
87732      652      748       3  882566948
9648       342       56       5  874984315
5078       325      187       3  891478455
61401      357      932       4  878952341
30775      177      568       3  880130915
57640      757      202       4  888445730
56553      733      125       2  879535814
92006      826      511       3  885690482
42561      435      890       1  884130883
4857         6      525       5  883601203
50421      664      152       3  878091463
65491      479      300       2  879459641
93436      634      292       3  876170101
83371      892       81       3  886608473
51976       23      526       3  874787116
17343      346      455       3  874948889
91203      807      998       3  893081656
47323      634      325       1  877974690
97513      745      603       4  880123243
69185      536       94       4  882363972
56576      579      877       1  880951594
70312      629       69       5  880117485

[25000 rows x 4 columns]

In [10]:
train_data

user_id  item_id  rating  timestamp
59561       59      290       3  888203750
21919      454      945       3  881960083
46952      159      250       3  881679988
30997        6      203       3  883602864
99002      883      238       4  891694218
49336      683      187       5  893286501
70861      843      225       2  879449256
63703      145      106       4  875270655
72127      503      174       5  880472250
34623      600     1228       2  888452490
28415      541      756       4  883866028
16197      303      218       4  879484695
65686      724      349       2  883757537
64843      493      234       5  884132037
63315      658       86       4  875147873
46537      663      405       3  889492877
81485      643      568       4  891447663
72364      486     1176       3  879874388
61071      339      503       4  891035093
90070      608      197       5  880405431
75374      456      265       3  881374048
42553      666      179       5  880139323
35960       90      310       3  891382240
49679      721      258       3  877135269
33066      456     1218       3  881374921
13055      298      213       3  884183130
39871      342      756       3  874984895
48574      467      246       5  879532534
61520      222      470       3  878181869
32317      488       28       4  891293805
...        ...      ...     ...        ...
10420      374      930       2  880394179
59964      648      678       3  884366792
21095      135      173       4  879857723
69177      851     1047       3  874789005
35504      496      659       3  876065822
84312      313      229       3  891028241
17188      435      443       3  884132777
52136      655      417       2  888771346
82271      745       50       2  880122928
92226      922       15       4  891453122
88544       49      477       2  888067727
81573      796      269       3  892610692
18030       13      821       3  882141393
41957      437      176       2  880143809
54009      724      872       1  883757537
51606      279      230       4  892865054
45321      154      211       4  879139002
41457      133      245       3  890588878
38470      542      818       4  886533112
36664      592      197       5  882955863
97259      521      204       4  884477853
17021      361      524       4  879440386
260        303      815       3  879485532
48919      660      120       1  891198996
8445       118      511       5  875384885
41859      130       67       4  876252064
23809      328      823       3  885049024
56733      682      568       3  888522575
70862      898      748       4  888294739
83262      436      144       5  887769444

[75000 rows x 4 columns]

In [11]:
#Create two user-item matrices, one for training and another for testing
def train_test_split(ratings):
    test = np.zeros(ratings.shape)
    train = ratings.copy()
    for user in range(ratings.shape[0]):
        test_ratings = np.random.choice(ratings[user, :].nonzero()[0], 
                                        size=10, 
                                        replace=False)
        train[user, test_ratings] = 0.
        test[user, test_ratings] = ratings[user, test_ratings]
        
    # Test and training are truly disjoint
    assert(np.all((train * test) == 0)) 
    return train, test

In [12]:
train,test=train_test_split(ratings)

In [13]:
train

array([[ 5.,  3.,  4., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  5.,  0., ...,  0.,  0.,  0.]])

In [55]:
pd.DataFrame(train)

0     1     2     3     4     5     6     7     8     9     ...   1672  \
0     5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...    0.0   
1     4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...    0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4     4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
5     4.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   4.0   0.0  ...    0.0   
6     0.0   0.0   0.0   5.0   0.0   0.0   5.0   5.0   5.0   4.0  ...    0.0   
7     0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   0.0  ...    0.0   
8     0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...    0.0   
9     4.0   0.0   0.0   4.0   0.0   0.0   4.0   0.0   4.0   0.0  ...    0.0   
10    0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   5.0   0.0  ...    0.0   
11    0.0   0.0   0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
12    3.0   3.0   0.0   5.0   1.0   0.0   2.0   4.0   0.0   0.0  ...    0.0   
13    0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   4.0   0.0  ...    0.0   
14    1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   4.0   0.0  ...    0.0   
15    5.0   0.0   0.0   5.0   0.0   0.0   5.0   5.0   5.0   0.0  ...    0.0   
16    4.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   3.0   0.0  ...    0.0   
17    5.0   0.0   0.0   3.0   0.0   5.0   0.0   5.0   5.0   0.0  ...    0.0   
18    0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
19    3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
20    5.0   0.0   0.0   0.0   2.0   0.0   5.0   0.0   5.0   0.0  ...    0.0   
21    0.0   2.0   0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
22    0.0   0.0   0.0   0.0   0.0   0.0   4.0   4.0   0.0   0.0  ...    0.0   
23    0.0   0.0   0.0   0.0   0.0   0.0   4.0   5.0   5.0   0.0  ...    0.0   
24    5.0   0.0   0.0   0.0   0.0   0.0   4.0   4.0   0.0   0.0  ...    0.0   
25    3.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...    0.0   
26    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...    0.0   
27    0.0   0.0   0.0   0.0   3.0   0.0   5.0   0.0   0.0   0.0  ...    0.0   
28    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
29    0.0   3.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...    0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
913   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
914   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
915   4.0   3.0   3.0   4.0   3.0   0.0   4.0   0.0   5.0   0.0  ...    0.0   
916   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...    0.0   
917   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
918   4.0   0.0   0.0   1.0   4.0   0.0   3.0   0.0   5.0   0.0  ...    0.0   
919   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
920   3.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0  ...    0.0   
921   5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
922   3.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...    0.0   
923   5.0   3.0   0.0   0.0   0.0   4.0   4.0   0.0   4.0   0.0  ...    0.0   
924   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
925   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
926   5.0   0.0   0.0   0.0   0.0   0.0   3.0   4.0   0.0   0.0  ...    0.0   
927   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
928   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
929   3.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0  ...    0.0   
930   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
931   4.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   5

In [14]:
train.shape

(943L, 1682L)

In [15]:
test

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [54]:
pd.DataFrame(test)

0     1     2     3     4     5     6     7     8     9     ...   1672  \
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
5     0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0  ...    0.0   
6     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
7     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
8     0.0   0.0   0.0   0.0   0.0   5.0   0.0   0.0   0.0   0.0  ...    0.0   
9     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
10    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
11    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
12    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...    0.0   
13    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
14    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
15    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
16    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
17    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
18    0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   0.0  ...    0.0   
19    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
20    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
21    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
22    5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
23    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
24    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
25    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
26    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
27    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
28    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
29    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
913   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
914   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
915   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
916   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
917   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
918   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
919   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
920   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
921   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
922   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
923   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
924   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
925   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
926   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
927   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   5.0   0.0  ...    0.0   
928   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
929   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
930   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
931   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0

In [16]:
test.shape

(943L, 1682L)

In [56]:
def similarity(ratings, kind='user', epsilon=1e-9):
    # epsilon -> small number for handling dived-by-zero errors
    if kind == 'user':
        sim = ratings.dot(ratings.T) + epsilon
    elif kind == 'item':
        sim = ratings.T.dot(ratings) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)
user_similarity = fast_similarity(train, kind='user')
item_similarity = fast_similarity(train, kind='item')

In [18]:
user_similarity.shape

(943L, 943L)

In [19]:
item_similarity.shape

(1682L, 1682L)

In [20]:
print(user_similarity[:4, :4])

[[ 1.          0.13312349  0.01690514  0.03957725]
 [ 0.13312349  1.          0.11048178  0.07411141]
 [ 0.01690514  0.11048178  1.          0.18483021]
 [ 0.03957725  0.07411141  0.18483021  1.        ]]


In [21]:
print(item_similarity[:4, :4])

[[ 1.          0.39661904  0.27836747  0.44297963]
 [ 0.39661904  1.          0.24931056  0.51058511]
 [ 0.27836747  0.24931056  1.          0.30387004]
 [ 0.44297963  0.51058511  0.30387004  1.        ]]


In [22]:
item_similaritydf=pd.DataFrame(item_similarity[:,:])
np.fill_diagonal(item_similaritydf.values,1)


In [23]:
user_similaritydf=pd.DataFrame(user_similarity[:,:])
np.fill_diagonal(user_similaritydf.values,1)

In [24]:
item_similaritydf.ix[:5,:5]

0         1         2         3         4         5
0  1.000000  0.396619  0.278367  0.442980  0.291341  0.133123
1  0.396619  1.000000  0.249311  0.510585  0.309866  0.092311
2  0.278367  0.249311  1.000000  0.303870  0.196881  0.122127
3  0.442980  0.510585  0.303870  1.000000  0.334487  0.078439
4  0.291341  0.309866  0.196881  0.334487  1.000000  0.041723
5  0.133123  0.092311  0.122127  0.078439  0.041723  1.000000

In [25]:
user_similaritydf.ix[:5,:5]

0         1         2         3         4         5
0  1.000000  0.133123  0.016905  0.039577  0.346876  0.417782
1  0.133123  1.000000  0.110482  0.074111  0.025103  0.214875
2  0.016905  0.110482  1.000000  0.184830  0.023080  0.079152
3  0.039577  0.074111  0.184830  1.000000  0.030481  0.059900
4  0.346876  0.025103  0.023080  0.030481  1.000000  0.245063
5  0.417782  0.214875  0.079152  0.059900  0.245063  1.000000

In [58]:
def predict(ratings, similarity, kind='user'):
    if kind == 'user':
        return similarity.dot(ratings) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif kind == 'item':
        return ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [60]:
item_prediction = predict(train, item_similarity, kind='item')
user_prediction = predict(train, user_similarity, kind='user')


In [28]:
pd.DataFrame(item_prediction[:9,:9])

0         1         2         3         4         5         6  \
0  1.141397  1.058837  1.102652  1.095331  1.004803  1.071558  1.131130   
1  0.203089  0.121052  0.167169  0.146737  0.135715  0.196708  0.190428   
2  0.097378  0.071475  0.090911  0.082855  0.081797  0.079169  0.104346   
3  0.048640  0.037963  0.045877  0.041956  0.041056  0.041750  0.051951   
4  0.606756  0.605679  0.524529  0.561174  0.519524  0.315977  0.562650   
5  0.863077  0.682895  0.671349  0.794942  0.638022  0.800029  0.827664   
6  1.695116  1.616643  1.457821  1.715405  1.519848  1.225576  1.686899   
7  0.256855  0.265025  0.225260  0.253551  0.217978  0.142851  0.256605   
8  0.063674  0.048062  0.054678  0.053967  0.047079  0.049110  0.066147   

          7         8  
0  1.080384  1.103776  
1  0.162012  0.209303  
2  0.083729  0.099699  
3  0.040660  0.046235  
4  0.552443  0.489746  
5  0.885704  0.897095  
6  1.758910  1.676739  
7  0.231189  0.224599  
8  0.059144  0.065470

In [29]:
pd.DataFrame(user_prediction[:9,:9])

0         1         2         3         4         5         6  \
0  2.257367  0.764510  0.413246  1.291277  0.463267  0.144860  2.011294   
1  1.748885  0.318813  0.275765  0.650474  0.241620  0.115630  1.398040   
2  1.300595  0.304483  0.226498  0.577905  0.236545  0.073234  1.204966   
3  1.535171  0.373442  0.263325  0.685914  0.277763  0.088536  1.404605   
4  2.445723  0.863532  0.410519  1.333072  0.483575  0.103427  2.036035   
5  2.094141  0.613821  0.321348  1.146698  0.373902  0.141672  1.807899   
6  2.190982  0.781827  0.367707  1.330434  0.471735  0.122658  1.956368   
7  2.165329  0.835527  0.369616  1.286146  0.441638  0.096014  1.971992   
8  1.832466  0.458882  0.308363  0.824553  0.292472  0.108951  1.800101   

          7         8  
0  1.370725  1.505705  
1  0.758886  1.244604  
2  0.634870  0.904458  
3  0.719774  0.970077  
4  1.430899  1.362690  
5  1.349927  1.508147  
6  1.468239  1.503007  
7  1.253526  1.298415  
8  0.948899  1.281389

In [30]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)
print('User-based CF MSE: ' + str(get_mse(user_prediction, test)))
print('Item-based CF MSE: ' + str(get_mse(item_prediction, test)))

User-based CF MSE: 8.3021035132
Item-based CF MSE: 11.4864299246


In [31]:
def predict_topk(ratings, similarity, kind='user', k=40):
    pred = np.zeros(ratings.shape)
    if kind == 'user':
        for i in range(ratings.shape[0]):
            top_k_users = [np.argsort(similarity[:,i])[:-k-1:-1]]
            for j in range(ratings.shape[1]):
                pred[i, j] = similarity[i, :][top_k_users].dot(ratings[:, j][top_k_users]) 
                pred[i, j] /= np.sum(np.abs(similarity[i, :][top_k_users]))
    if kind == 'item':
        for j in range(ratings.shape[1]):
            top_k_items = [np.argsort(similarity[:,j])[:-k-1:-1]]
            for i in range(ratings.shape[0]):
                pred[i, j] = similarity[j, :][top_k_items].dot(ratings[i, :][top_k_items].T) 
                pred[i, j] /= np.sum(np.abs(similarity[j, :][top_k_items]))        
    
    return pred

In [32]:
pred = predict_topk(train, user_similarity, kind='user', k=40)
print('Top-k User-based CF MSE: ' + str(get_mse(pred, test)))

pred = predict_topk(train, item_similarity, kind='item', k=40)
print('Top-k Item-based CF MSE: ' + str(get_mse(pred, test)))

Top-k User-based CF MSE: 6.39152518934
Top-k Item-based CF MSE: 7.67493005136


In [33]:
preduser = predict_topk(train, user_similarity, kind='user', k=40)

In [34]:
preditem = predict_topk(train, item_similarity, kind='item', k=40)

In [35]:
preduserdf=pd.DataFrame(preduser)
preditemdf=pd.DataFrame(preditem)

In [36]:
preduserdf.ix[:9,:9]

0         1         2         3         4         5         6  \
0  3.670815  2.080415  1.427529  3.079005  1.272237  0.253549  4.093087   
1  2.055948  0.000000  0.334565  0.178872  0.134154  0.204825  1.502828   
2  0.000000  0.000000  0.062641  0.000000  0.000000  0.000000  0.194098   
3  0.231667  0.000000  0.000000  0.038355  0.000000  0.000000  0.517867   
4  3.908517  2.384128  0.681018  2.241913  0.776510  0.000000  2.997300   
5  2.637489  0.380621  0.436738  1.946777  0.517286  0.500652  2.623875   
6  2.650859  1.115593  0.534518  2.350047  0.730368  0.162450  2.676474   
7  1.935639  1.832584  0.301877  2.162941  0.370311  0.085034  2.384413   
8  1.524634  0.000000  0.041734  0.177702  0.083467  0.000000  2.034642   
9  2.682507  0.766067  0.612566  2.443319  0.565899  0.481437  2.725625   

          7         8         9  
0  2.612892  2.848173  1.023369  
1  0.118569  1.798155  0.633380  
2  0.000000  0.202468  0.110032  
3  0.000000  0.174088  0.138376  
4  1.233615  1.030184  0.705891  
5  2.697689  2.855271  1.397455  
6  2.648628  2.299553  1.227416  
7  0.634629  0.654077  0.278046  
8  0.418107  1.059885  0.348809  
9  2.392286  2.787686  1.134120

In [37]:
preditemdf.ix[:9,:9]

0         1         2         3         4         5         6  \
0  3.481749  2.407669  2.327464  3.074545  2.199085  1.922074  3.446324   
1  0.458925  0.000000  0.097036  0.000000  0.000000  0.299786  0.473590   
2  0.113302  0.000000  0.000000  0.000000  0.000000  0.000000  0.150313   
3  0.151793  0.000000  0.112663  0.000000  0.069929  0.000000  0.230336   
4  2.023382  1.648071  0.964442  1.650208  0.689954  0.000000  1.724633   
5  2.203834  0.420012  0.712152  2.295565  0.537943  0.445892  2.338949   
6  3.400014  3.158582  1.469494  4.292636  2.769416  0.078023  3.783723   
7  1.323560  1.720888  0.554090  1.620469  0.776032  0.000000  1.415582   
8  0.249851  0.136230  0.209972  0.122971  0.108528  0.000000  0.319039   
9  1.530524  0.780016  0.912680  2.576575  1.516392  0.366461  2.402542   

          7         8         9  
0  3.023092  2.849722  2.367517  
1  0.000000  0.634689  0.567724  
2  0.102275  0.240923  0.000000  
3  0.116562  0.216443  0.000000  
4  1.504640  0.950768  0.667995  
5  2.512492  2.669257  1.981432  
6  4.322868  3.541867  2.216113  
7  0.840486  0.731578  0.279233  
8  0.116562  0.342878  0.183875  
9  2.000057  2.415584  1.975876

In [38]:
idx_to_movie = {}
with open('u.item', 'r') as f:
    for line in f.readlines():
        info = line.split('|')
        idx_to_movie[int(info[0])-1] = info[1]
        
def top_k_movies(similarity, mapper, movie_idx, k):
    return [mapper[x] for x in np.argsort(similarity[movie_idx,:])[:-k-1:-1]]

In [57]:
idx_to_movie

{0: 'Toy Story (1995)',
 1: 'GoldenEye (1995)',
 2: 'Four Rooms (1995)',
 3: 'Get Shorty (1995)',
 4: 'Copycat (1995)',
 5: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 6: 'Twelve Monkeys (1995)',
 7: 'Babe (1995)',
 8: 'Dead Man Walking (1995)',
 9: 'Richard III (1995)',
 10: 'Seven (Se7en) (1995)',
 11: 'Usual Suspects, The (1995)',
 12: 'Mighty Aphrodite (1995)',
 13: 'Postino, Il (1994)',
 14: "Mr. Holland's Opus (1995)",
 15: 'French Twist (Gazon maudit) (1995)',
 16: 'From Dusk Till Dawn (1996)',
 17: 'White Balloon, The (1995)',
 18: "Antonia's Line (1995)",
 19: 'Angels and Insects (1995)',
 20: 'Muppet Treasure Island (1996)',
 21: 'Braveheart (1995)',
 22: 'Taxi Driver (1976)',
 23: 'Rumble in the Bronx (1995)',
 24: 'Birdcage, The (1996)',
 25: 'Brothers McMullen, The (1995)',
 26: 'Bad Boys (1995)',
 27: 'Apollo 13 (1995)',
 28: 'Batman Forever (1995)',
 29: 'Belle de jour (1967)',
 30: 'Crimson Tide (1995)',
 31: 'Crumb (1994)',
 32: 'Desperado (1995)',
 33: 'D

In [39]:
idx = 0 # Toy Story
movies_itemsimilarity = top_k_movies(item_similarity, idx_to_movie, idx,k=10)

In [40]:
movies_itemsimilarity

['Toy Story (1995)',
 'Star Wars (1977)',
 'Return of the Jedi (1983)',
 'Independence Day (ID4) (1996)',
 'Raiders of the Lost Ark (1981)',
 'Rock, The (1996)',
 'Willy Wonka and the Chocolate Factory (1971)',
 'Star Trek: First Contact (1996)',
 'Empire Strikes Back, The (1980)',
 'Mission: Impossible (1996)']

In [41]:
idx = 0 # 
movies = top_k_movies(preditem, idx_to_movie, idx,k=15)

In [42]:
movies

['Star Wars (1977)',
 'Mystery Science Theater 3000: The Movie (1996)',
 'Jaws (1975)',
 'Wrong Trousers, The (1993)',
 'Blade Runner (1982)',
 'Monty Python and the Holy Grail (1974)',
 'Nikita (La Femme Nikita) (1990)',
 'Reservoir Dogs (1992)',
 'Star Trek: First Contact (1996)',
 'Willy Wonka and the Chocolate Factory (1971)',
 'Brazil (1985)',
 'Alien (1979)',
 'Godfather, The (1972)',
 'Aliens (1986)',
 'Pulp Fiction (1994)']

In [43]:
idx = 0 # 
movies = top_k_movies(preduser, idx_to_movie, idx,k=15)

In [44]:
movies

['Star Wars (1977)',
 'Raiders of the Lost Ark (1981)',
 'Princess Bride, The (1987)',
 'Monty Python and the Holy Grail (1974)',
 'Fargo (1996)',
 'Aliens (1986)',
 'Pulp Fiction (1994)',
 'Blade Runner (1982)',
 'Alien (1979)',
 'Twelve Monkeys (1995)',
 'Usual Suspects, The (1995)',
 'Empire Strikes Back, The (1980)',
 'Shawshank Redemption, The (1994)',
 'Star Trek: The Wrath of Khan (1982)',
 'Silence of the Lambs, The (1991)']